export const ADD_ONE_TO_COUNTER = 'ADD_ONE_TO_COUNTER'
export const MINUS_ONE_FROM_COUNTER = 'MINUS_ONE_FROM_COUNTER'
export const CUSTOMER_ADD_COUNTER = 'CUSTOMER_ADD_COUNTER'

export const UPDATE_CART_COUNT = 'UPDATE_CART_COUNT'
export const ADD_TO_CART_LIST = 'ADD_TO_CART_LIST';